repos:
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.740'
    hooks:
      - id: mypy
        exclude: '.*tests/.*|.*docs/.*'
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.7
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.4
    hooks:
    - id: flake8
