dist: xenial
sudo: false
language: python
python:
  - "3.7"
  - "3.8"
  - "3.8-dev"
# Commenting out until upstream libraries are fixed for 3.9 breaking changes.
#  - "nightly"

stages:
  - linting
  - test

cache:
  directories:
    - "$HOME/.cache/pre-commit"
    - "$HOME/.cache/pypoetry"
    - "$HOME/virtualenv/"

install:
  - pip install --upgrade pip
  - pip install poetry
  - poetry install -v

script:
  - pytest tests typic --doctest-modules --cov --cov-config=.coveragerc --cov-report xml

after_success:
  - codecov
